blank_issues_enabled: false
contact_links:
  - name: ๐ฌ ุงุฏู ฺฉุณุจโูฺฉุงุฑ ุง ุงูุฒุงุด ุฏุณุชุฑุณ
    url: https://divar.ir/kenar/management/issues
    about: ุจุฑุง ุงุฏูโูุง ฺฉุณุจโูฺฉุงุฑ ุงุจุฒุงุฑ/ุงูุฒููู ุง ุฏุฑุฎูุงุณุช ุฏุณุชุฑุณ ุจู ูพุฑูุดูโูุงุ ูุทูุงู ุฏุฑ ูพูู ฺฉูุงุฑ ุฏูุงุฑ ุชฺฉุช ุจุฒูุฏ.
  - name: โ ุณูุงูุงุช ูู ู ูพุดุชุจุงู
    url: https://divar.ir/kenar/management/issues
    about: ุณูุงูุงุช ุฎูุฏ ุฏุฑ ููุฑุฏ ูุญููโ ูพุงุฏูโุณุงุฒ ุณุณุชู ุฑุง ุฏุฑ ูพูู ฺฉูุงุฑ ุฏูุงุฑ ุซุจุช ฺฉูุฏ.
